Adjust sonar job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -113,13 +113,27 @@ jobs:
           name: Install dependencies
           command: npm install
 
+       # Run Jest to generate the coverage report
+      - run:
+          name: Run tests with coverage
+          command: npm test -- --coverage
+      # Verify the lcov.info file exists
+      - run:
+          name: Verify coverage report
+          command: |
+            if [ ! -f coverage/lcov.info ]; then
+              echo "Coverage report not found! Ensure tests generate coverage/lcov.info.";
+              exit 1;
+            fi
+
       - run:
           name: Run sonar analysis
-          command: npm run test:coverage \
+          command: npx sonar-scanner \
             -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
             -Dsonar.organization=${SONAR_ORGANIZATION} \
             -Dsonar.host.url=${SONAR_HOST_URL} \
-            -Dsonar.login=${SONAR_TOKEN} || echo "Sonar analysis failed, but skipping job when failed." && exit 0
+            -Dsonar.login=${SONAR_TOKEN} \
+            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info || echo "Sonar analysis failed, but skipping job when failed." && exit 0
 
       - jira/notify:
           pipeline_id: << pipeline.id >>
